# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: itcode-dev/eslint-config Tag

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 업데이트할 버전 선택
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Version Update
        run: |
          echo "@itcode.dev/eslint-config ${{ github.event.inputs.version }} 업그레이드"

          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "${{ vars.NAME }}"

          npm version ${{ github.event.inputs.version }}
          git push origin --tag
          git push
